env:
  global:
    - CC_TEST_REPORTER_ID=392653690efc9e65af92588e76d5d83f4c5660d20ee402b591b7df0035b60b7d
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
#Instruction to perform before
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# command to run tests
script: 
  - coverage run run_tests.py
after_success: 
  - ./cc-test-reporter after-build --coverage-input-type .coverage --exit-code $EXIT_CODE
  - coveralls